# Generated by Django 4.0.4 on 2022-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0006_alter_client_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoice',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
