# Generated by Django 4.0.4 on 2022-04-21 14:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0007_alter_client_invoice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bouquet',
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
